FROM openjdk:11

RUN mkdir /app
COPY ./build/libs/ichirin-1.0-SNAPSHOT.jar /app/ichirin-api.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar","/app/ichirin-api.jar"]