spring:
  jpa:
    hibernate:
      database: HSQLDB
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:ichirin
    username: ichirin
    password: password
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  application:
    name: Ichirin-Backend

ichirin:
  authentication:
    secret: dcb231c1-6c71-43ff-91dc-9c66b6ce7e5d
    expire: 3600000
      #1 hour