spring:
  jpa:
    hibernate:
      database: HSQLDB
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:ichirin
    username: ichirin
    password: password
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  application:
    name: Ichirin-Backend