spring:
  datasource:
    url: jdbc:postgresql://ichirin-postgres:5432/ichirin
    username: ichirin
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect;
  application:
    name: Ichirin-Backend

ichirin:
  authentication:
    secret: dcb231c1-6c71-43ff-91dc-9c66b6ce7e5d
    expire: 3600000
      #1 hour