import Head from 'next/head';
import Navbar from '../components/UI/Navbar';
import Topbar from '../components/UI/Topbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ichirin no Hana Yuri</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar/>
      <Topbar/>
    </>
  );
}
